# Numpy

Numpy je knihovna pro práci s vícerozměrnými poli (tenzory). Poskytuje efektivní a snadno použitelné uživatelské rozhraní ke standarním operacím s vícerozměrnými poli a k operacím lineární algebry. V tomto sešitu jsou uvedeny pouze základní funkce a koncepty. Kompletní přehled funkcí najdete v [referenční dokumentaci](https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html)


Dále předpokládáme import knihovny ve tvaru:


In [1]:
import numpy as np

## Array
Základní třída, která vlastní data doplňuje o metadata o jejich organizaci. Různé operace na řezání a transpozici dat fakticky jen mění metadata.

In [3]:
# Konverze ze standarnich Pythnonich typu.
a = np.array( [ range(3), range(1,4)])
print(a)

# Dimenze pole
a.shape

[[0 1 2]
 [1 2 3]]


(2, 3)

### Přetížené operátory
Operace probíhají po elementech. Objekty s menším počtem dimenzí jsou opakovány, tak aby se shodoval tvar.

In [4]:
# násobení skalárem
b = 2 * a
b

array([[0, 2, 4],
       [2, 4, 6]])

In [33]:
# Skalár je konvertován na matici (2,3):
one = np.ones( (2,3) )
one

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [35]:
two = 2 * one
two

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [36]:
two * a
# Všiměte si jiného typu prvků, zde máme float, v poli 'a' je int.

array([[ 0.,  2.,  4.],
       [ 2.,  4.,  6.]])

In [37]:
# typ prvků
a.dtype

dtype('int64')

In [38]:
# type lze určit v konstruktoru
np.array(a, dtype=float)

array([[ 0.,  1.,  2.],
       [ 1.,  2.,  3.]])

In [39]:
# Jiné operátory fungují stejně
a + b

array([[0, 3, 6],
       [3, 6, 9]])

In [42]:
# I funkce lze aplikovat po jednotlivých elementech:
np.sin(np.pi * a / 2)

array([[  0.00000000e+00,   1.00000000e+00,   1.22464680e-16],
       [  1.00000000e+00,   1.22464680e-16,  -1.00000000e+00]])

### Array indexing and slicing
Podpora více indexů najednou v hranatých závorkách pro indexování vícerozměrných polí.

Řez ve formě `[start : end : step]` vybere v jedné dimenzi pouze indexy začínající `start`, s krokem `step` a menší než `end`.

In [12]:
# Více indexů povoleno
a[0, 1]

1

In [13]:
# Pomocí řezů lze vybírat pod výběry.
# první sloupec
a[:, 0]

array([0, 1])

In [16]:
# Druhý řádek, prvky 0..2
a[1, 0:2]

array([1, 2])

In [18]:
# Poslední dva prvky druhého řádku
a[1, -3:-1]

array([1, 2])

In [5]:
# První řádek pozpátku.
a[0,::-1]

array([2, 1, 0])

In [6]:
a[0, ...]

array([0, 1, 2])

### Array reshaping

In [11]:
# Rozbalení dat do prostého pole, může být vnitřně realizováno jen pomocí metadat.
# ... vrátí se "view".
b = a.ravel()
b[0] =10
a

array([[10,  1,  2],
       [ 1,  2,  3]])

In [14]:
# Stejné dělá metoda flatten, ale nyní vrací kopii skutčeně rozbalených dat. 
b = a.flatten()
b[0] = 100
a

array([[10,  1,  2],
       [ 1,  2,  3]])

In [23]:
# Změna tvaru pomocí přiřazení do attributu shape:
b.shape = (3, 2)
b

array([[0, 1],
       [2, 1],
       [2, 3]])

In [15]:
# transpozice
a.T
a.transpose()

array([[10,  1],
       [ 1,  2],
       [ 2,  3]])

In [ ]:
# Zkusit:
transpose(xyz, axes = )

### Array stacking
Posazení dvou matic (polí) nad sebe, vedle sebe ... 

In [17]:
a

array([[10,  1,  2],
       [ 1,  2,  3]])

In [20]:
vec = a.ravel()
vec.shape

(6,)

In [21]:
vec.shape = (1,6)

In [23]:
vec[:, None]

array([[[10,  1,  2,  1,  2,  3]]])

In [ ]:
vec

## Basic operations
Get help and try functions:
- min(), max(), maximum(), minimum()
- average(), mean()
- diff()
- dot()
- sum(), prod(), cumsum(), cumprod()

## Broadcasting
[Numpy broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#broadcasting)

### Linear algebra

In [24]:
import numpy.linalg as la

## Klíčové funkce

- la.dot() ... stejne jako np.dot()
- la.inner(), la.outer(), la.kron()
- la.norm()
- la.solve(), la.qr()
- la.eig(), la.svd()