# Numpy

Numpy je knihovna pro práci s vícerozměrnými poli (tenzory). Poskytuje efektivní a snadno použitelné uživatelské rozhraní ke standarním operacím s vícerozměrnými poli a k operacím lineární algebry. V tomto sešitu jsou uvedeny pouze základní funkce a koncepty. Kompletní přehled funkcí najdete v [referenční dokumentaci](https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html)

Další zdroje:
- [Stanford lecture](https://web.stanford.edu/~schmit/cme193/lec/lec5.pdf)

- [100 cvičení z Numpy](http://yvesguidet.no-ip.biz/complementsMureaux/100_numpy_exercises.pdf)

- [Python and SciPy lecture notes](https://hal.inria.fr/hal-01206546/file/ScipyLectures-simple.pdf)

Dále předpokládáme import knihovny ve tvaru:


In [2]:
import numpy as np

## Array
Základní třída, která vlastní data doplňuje o metadata o jejich organizaci. Různé operace na řezání a transpozici dat fakticky jen mění metadata.

In [3]:
# Konverze ze standarnich Pythnonich typu.
list_matrix =[ list(range(3)), list(range(1,4))]
print(list_matrix)
a = np.array(list_matrix)
print(a, 'type', type(a))


# Dimenze pole
a.shape

[[0, 1, 2], [1, 2, 3]]
[[0 1 2]
 [1 2 3]] type <class 'numpy.ndarray'>


(2, 3)

### Inicializace array

In [32]:
# sekvence: počátek, konec, krok
print("arange: ", np.arange(1.1, 10, 2.1))

# sekvence: počátek, konec, počet bodů
print("linspace: ", np.linspace(1.1, 10, 4))

# zeros, ones, eye, full
print("zeros :\n", np.zeros((2,4)))
print("ones :\n", np.ones((2,4)))
print("full :\n", np.full((2,4), 3.14))

# jednotkova matice
print("eye :\n", np.eye(4))

arange:  [ 1.1  3.2  5.3  7.4  9.5]
linspace:  [  1.1          4.06666667   7.03333333  10.        ]
zeros :
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
ones :
 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
full :
 [[ 3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14]]
eye :
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


### Array - atributy

    a.ndim
    a.dtype
    a.shape
    a.size

### Přetížené operátory
Operace probíhají po elementech. Objekty s menším počtem dimenzí jsou opakovány, tak aby se shodoval tvar.

In [3]:
# násobení skalárem
b = 2 * a
b

array([[0, 2, 4],
       [2, 4, 6]])

In [4]:
# Skalár je konvertován na matici (2,3):
one = np.ones( (2,3) )
one

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
two = 2 * one
two

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [6]:
two * a
# Všiměte si jiného typu prvků, zde máme float, v poli 'a' je int.

array([[ 0.,  2.,  4.],
       [ 2.,  4.,  6.]])

In [7]:
# typ prvků
a.dtype

dtype('int64')

In [8]:
# type lze určit v konstruktoru
np.array(a, dtype=float)

array([[ 0.,  1.,  2.],
       [ 1.,  2.,  3.]])

In [9]:
# Jiné operátory fungují stejně
a + b

array([[0, 3, 6],
       [3, 6, 9]])

In [10]:
# I funkce lze aplikovat po jednotlivých elementech:
np.sin(np.pi * a / 2)

array([[  0.00000000e+00,   1.00000000e+00,   1.22464680e-16],
       [  1.00000000e+00,   1.22464680e-16,  -1.00000000e+00]])

### Broadcasting
Obecná pravidla konverze polí menší dimenze na pole vyšší dimenze při (binárních) operacích.

[Numpy broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#broadcasting)

### Array indexing and slicing
Podpora více indexů najednou v hranatých závorkách pro indexování vícerozměrných polí.

Řez ve formě `[start : end : step]` vybere v jedné dimenzi pouze indexy začínající `start`, s krokem `step` a menší než `end`.

In [11]:
# Více indexů povoleno
a[0, 1]

1

In [12]:
# Pomocí řezů lze vybírat pod výběry.
# první sloupec
a[:, 0]

array([0, 1])

In [13]:
# Druhý řádek, prvky 0..2
a[1, 0:2]

array([1, 2])

In [14]:
# Poslední dva prvky druhého řádku
a[1, -3:-1]

array([1, 2])

In [15]:
# První řádek pozpátku.
a[0,::-1]

array([2, 1, 0])

In [16]:
a[0, ...]

array([0, 1, 2])

In [15]:
# Konverze vektoru na matici, přidání axis
b=a[0]
print(b[None,:])
print(b[:,None])

[[0 1 2]]
[[0]
 [1]
 [2]]


### Array reshaping

In [17]:
# Rozbalení dat do prostého pole, může být vnitřně realizováno jen pomocí metadat.
# ... vrátí se "view".
b = a.ravel()
b[0] =10
a

array([[10,  1,  2],
       [ 1,  2,  3]])

In [18]:
# Stejné dělá metoda flatten, ale nyní vrací kopii skutčeně rozbalených dat. 
b = a.flatten()
b[0] = 100
a

array([[10,  1,  2],
       [ 1,  2,  3]])

In [19]:
# Změna tvaru pomocí přiřazení do attributu shape:
b.shape = (3, 2)
b

array([[100,   1],
       [  2,   1],
       [  2,   3]])

In [20]:
# transpozice
a.T
a.transpose()

array([[10,  1],
       [ 1,  2],
       [ 2,  3]])

In [33]:
# Zkusit:
xy = np.outer(np.arange(1,3,1), np.arange(1,4,2))
print("xy: \n", xy)
xyz = np.dot(xy[:,:,None], np.arange(1,5,3)[None,:])
print("\nxyz: \n", xyz)
print("\ntranspose: \n",np.transpose(xyz, (1,0,2)))

xy: 
 [[1 3]
 [2 6]]

xyz: 
 [[[ 1  4]
  [ 3 12]]

 [[ 2  8]
  [ 6 24]]]

transpose: 
 [[[ 1  4]
  [ 2  8]]

 [[ 3 12]
  [ 6 24]]]


## Operace s více poli.


### Array stacking
Posazení dvou matic (polí) nad sebe, vedle sebe ... 

In [40]:
a, b

(array([[0, 1, 2],
        [1, 2, 3]]), array([0, 1, 2]))

In [49]:
# Více polí stejného shape na pole vyšší dimenze. 
# Např. z vektorů udělat matici (vektory jako sloupce)
np.stack((a[0], a[1], b), axis=1)

array([[0, 1, 0],
       [1, 2, 1],
       [2, 3, 2]])

In [50]:
# To samé v řádcích
np.stack((a[0], a[1], b), axis=0)

array([[0, 1, 2],
       [1, 2, 3],
       [0, 1, 2]])

In [48]:
# Více polí různý shape, zachování dimenze. Stejný shape kolmo na axise slučování.
np.concatenate((a, b[None,:]), axis=0) # V axis 1 stejný shape. 

array([[0, 1, 2],
       [1, 2, 3],
       [0, 1, 2]])

## Basic operations
Get help and try functions:
- min(), max(), maximum(), minimum()
- average(), mean()
- diff()
- dot()
- sum(), prod(), cumsum(), cumprod()

### Linear algebra

In [ ]:
import numpy.linalg as la

## Klíčové funkce

Numpy:
- np.dot()
- np.inner(), np.outer(), np.kron()
- la.norm()
- la.solve(), la.lu(), la.cholesky(), la.qr()
- la.eig(), la.svd()

np.fft module

In [ ]:
c = [[1, 12], [3,4],[1,4]]
nc = np.array(c)
nc
nc[1]

In [ ]:
np.minimum(nc[0, 1:], nc[1,])

# Cvičení

1. Nastudujte a vyzkoušejte si základní funkce z modulu np.random:
   
   random, rand, seed, choice
   
2. Vygenerujte:
   
   - náhodnou matici A, shape (3, 3)
   - náhodný vektor b, shape (3, )
   
3. vyřešte soustavu $Ax=b$ a ověřte řešení pomocí výpočtu $Ax - b$

4. Vygenerujte pole dvojic náhodných bodů (úseček) v jednotkovém čtverci, jako matici (N, 2, 2)

5. Vypočtěte pole délek úseček (jednořádkový  kód).

6. Vytvořte pole X, Y, Z, kde X obsahuje x souřednice prvních bodů, Y je y souřadnice prvních bodů, z je logaritmus délek úseček.

7. Vypočtěte průmernou délku úseček a směrodatnou odchylku.
